id: P4B25E8DA
initial_creation_type: ocr
source_metadata:
  volumes:
    1f11e49448b4423090df0c66ad534b22:
      base_file: v039.txt
      image_group_id: I1PD95884
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1625
      volume_number: 39
